<?php

/**
 * @file
 * Contains emergency_alerts.module..
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function emergency_alerts_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the emergency_alerts module.
    case 'help.page.emergency_alerts':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('Show emergency alerts of varying severity') . '</p>';
      return $output;

    default:
  }
}

/**
 * Implements hook_theme_suggestions_html_alter().
 */
function emergency_alerts_theme_suggestions_html_alter(array &$suggestions, array &$variables) {
  $config = \Drupal::config('emergency_alerts.settings');
  if ($config->get('override')) {
    $is_admin = \Drupal::service('router.admin_context')->isAdminRoute();
    if (!$is_admin) {
      $suggestions[] = 'html__emergency_alert';

      $message = $config->get('alert_message');

      $variables['title'] = $config->get('alert_title');
      $variables['message'] = [
        '#type' => 'markup',
        '#markup' => $message['value'],
      ];
      $variables['alert_level'] = $config->get('alert_level');
    }
  }
}

/**
 * Implements hook_page_attachements() to make sure config cache tag goes on every page.
 */
function emergency_alerts_page_attachments(array &$page) {
  $page['#cache']['tags'][] = 'config:emergency_alerts.settings';
}

/**
 * Implements hook_theme().
 */
function emergency_alerts_theme($existing, $type, $theme, $path) {
  return [
    'emergency_alert' => [
      'variables' => [
        'title' => 'Alert',
        'message' => [],
        'alert_level' => NULL,
      ],
    ],
  ];
}
